authors:
  wim_wenigerkind:
    name: Wim Wenigerkind
    description: Developer and DevOps enthusiast
    avatar: https://images.wimwenigerkind.com/wimwenigerkind-transparent-icon.png
    url: https://wimwenigerkind.com
