site_name: Docs
theme:
    name: material
    logo: https://images.wimwenigerkind.com/wimwenigerkind-transparent-icon.png
    favicon: https://images.wimwenigerkind.com/wimwenigerkind-transparent-icon.png
    features:
        - navigation.footer
        - content.code.copy
        - content.code.select
        - content.code.annotate
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: https://wimwenigerkind.com
markdown_extensions:
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: Copyright &copy; 2024 Wim Wenigerkind
nav:
    - Home: https://wimwenigerkind.com
    - Docker:
          - Docker: docker/docker.md
          - Docker Compose:  docker/docker-compose.md
          - Docker Compose Scripts:
              - Portainer: docker/portainer.md
              - Wireguard + Wireguard Ui: docker/wireguard-and-ui.md
              - Uptime Kuma: docker/uptime-kuma.md
              - Guacamole: docker/guacamole.md
              - Homepage: docker/homepage.md
              - Keycloak: docker/keycloak.md
    - Proxmox: proxmox.md
    - apt:
          - OpenSSH-Server: openssh-server.md
    - MkDocs: mkdocs.md
    - piHole: pihole.md
    - Git: git.md
    - Docker Hub Docs:
          - Docker Hub: docker-hub/docker-hub.md
          - Symfony 7 Pipeline: docker-hub/symfony-7-pipeline.md
          - Minecraft Server: docker-hub/minecraft.md
    - Changelog: changelog.md