name: Deploy Unstable Version to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-unstable"
  cancel-in-progress: true

jobs:
  deploy-unstable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Nix
      uses: cachix/install-nix-action@v26
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: devenv
    
    - name: Install DevEnv
      run: nix profile install nixpkgs#devenv
    
    - name: Configure git
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
    
    - name: Deploy unstable version
      run: |
        devenv shell mike deploy --push unstable